services:
  postgres:
    image: postgres:16-alpine
    container_name: family_recipes_db
    environment:
      POSTGRES_USER: family_recipes_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: family_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_recipes_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: family_recipes_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: family_recipes_backend
    environment:
      - SECRET_KEY_BASE=965ffd588f61437a2aa32d8ad605b7b0deb76a03f085b1641c0aa652da3efdf287ca14d4c70888ac100b8790085eb7ce01b366758451ae259ccdb00d9bb88148
      - RAILS_ENV=production
      - DATABASE_HOST=postgres  # Matches the service name at the top of your file
      - DATABASE_USERNAME=family_recipes_user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=family_recipes
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ollama
    volumes:
      - ./backend:/app
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: family_recipes_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/srv/app

volumes:
  postgres_data:
  ollama_data:
